# Generated by Django 3.2.5 on 2021-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_title', models.CharField(max_length=100)),
                ('vote_date', models.DateField(verbose_name='date published')),
                ('vote_explain', models.TextField()),
                ('rank', models.IntegerField(default=0)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
