# Generated by Django 3.2.5 on 2021-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='booklist',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booklist',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
