# Generated by Django 3.2.5 on 2021-07-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20210728_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklist', to='vote.vote'),
        ),
    ]
