# Generated by Django 3.2.5 on 2021-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20210728_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='vote',
        ),
        migrations.AddField(
            model_name='booklist',
            name='vote',
            field=models.ManyToManyField(related_name='booklist', to='vote.Vote'),
        ),
    ]
