# Generated by Django 3.2.5 on 2021-08-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20210810_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votetable', to='vote.booklist')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votetable', to='vote.vote')),
            ],
        ),
    ]
