# Generated by Django 3.2.5 on 2021-08-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_votetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteTable',
        ),
    ]
