# Generated by Django 3.2.6 on 2021-08-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qinquiry',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
