# Generated by Django 3.2.5 on 2021-08-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20210728_1917'),
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='vote.booklist'),
        ),
    ]
