# Generated by Django 3.2.5 on 2021-07-31 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대출회원'),
        ),
        migrations.AddField(
            model_name='bookwhere',
            name='book_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.bookclassinfo'),
        ),
    ]
