# Generated by Django 3.2.5 on 2021-07-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclassinfo',
            name='department',
            field=models.CharField(max_length=30, verbose_name='수업개설학과'),
        ),
        migrations.AlterField(
            model_name='bookclassinfo',
            name='pubdate',
            field=models.DateField(null=True, verbose_name='출판일'),
        ),
    ]
