# Generated by Django 3.2.5 on 2021-08-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210730_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookwhere',
            name='book_info_id',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookClassInfo',
        ),
        migrations.DeleteModel(
            name='BookWhere',
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
