# Generated by Django 3.2.6 on 2021-08-07 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='wishes',
            field=models.ManyToManyField(related_name='wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
